name: bucket_pull_request
on:
  pull_request:
    branches:
      - master
jobs:
  bucket_pull_request:
    env:
      BUCKET_NAME: 'jekyll-ipfs-blog'
    runs-on: ubuntu-latest
    name: Create a Textile Bucket
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Make build destination directory
        run: mkdir -vp ~/www/jekyll
    - name: Jekyll Build
      uses: gha-utilities/jekyll-build@v0.0.2
      with:
        source: ./
        destination: ~/www/jekyll
    - name: Bucket push action
      id: push
      uses: textileio/github-action-bucket-push@master
      with:
        bucket-name: '${{ env.BUCKET_NAME }}-${{ github.event.pull_request.id }}'
        path: '~/www/jekyll/*'
        token: ${{ secrets.TEXTILE_AUTH_TOKEN }}
    - name: Get the output CID
      run: echo "The CID was ${{ steps.push.outputs.cid }}"
    - name: Get the Bucket URL
      run: echo "The Bucket URL is ${{ steps.push.outputs.url }}"
